### ISSUE TITLE
Unable to run Android app ( chaquopy hello)

### ISSUE THREAD

**Issue by Raghu17s** [chaquo/chaquopy-hello#12] opened 2019-11-17 14:09 UTC
Hi,

I have downloaded chaquopy-hello and imported it in an android studio. I have installed python plugin too. While running the app it shows en error Excetutable is not specified. 

The following error shows in "edit configuration" whale running. 

And in "hello.py" it shows "No python interpreter configured for the module" on the top.

![image](https://user-images.githubusercontent.com/34702809/69008567-c936fd00-0971-11ea-870d-44cd08058960.png)

**Comment by mhsmith** [comment] 2019-11-18 17:47
Duplicate of https://github.com/chaquo/chaquopy/issues/164.

**Closed by mhsmith** 2019-11-18 17:47 UTC
